version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.6.0   # (1)
    working_directory: ~/repo
    steps:
      - checkout
      # ... steps for building/testing app ...

      # build and push Docker image
      - run: |
          docker build -t hello-ci-workflow:0.1.1 .     

      # deploy the image
      - run: docker push hello-ci-workflow:0.1.1