version: 2
jobs:
 build:
   machine: true
   docker:
     # specify the version you desire here
     - image: circleci/node:11.6.0

   steps:
     - checkout

     # build the application image
     - run: docker build -t hello-ci-workflow:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push hello-ci-workflow:$CIRCLE_BRANCH